name: openmap-brainage
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - ca-certificates=2024.9.24
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.5
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - packaging=24.1
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=3.10.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - antspyx==0.4.2
      - appdirs==1.4.4
      - array-record==0.4.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==24.2.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - chart-studio==1.1.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colored==1.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.36
      - deprecated==1.2.15
      - dm-control==1.0.23
      - dm-env==1.6
      - dm-reverb==0.12.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - easydict==1.11
      - einops==0.7.0
      - etils==1.3.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - google-auth==2.35.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.65.0
      - gputil==1.4.0
      - grpcio==1.67.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h5py==3.11.0
      - hpt==0.0.1
      - huggingface-hub==0.26.2
      - humanize==4.10.0
      - hydra-core==1.3.2
      - hydra-joblib-launcher==1.2.0
      - idna==3.10
      - imageio==2.27.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - ipython==8.12.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - keras==2.13.1
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lazy-loader==0.4
      - libclang==18.1.1
      - lxml==4.9.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mujoco==3.2.3
      - mujoco-py==2.1.2.14
      - networkx==3.1
      - nibabel==5.2.1
      - numcodecs==0.12.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - opt-einsum==3.4.0
      - pandas==2.0.3
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.24.1
      - pluggy==1.5.0
      - portpicker==1.6.0
      - promise==2.3
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==6.1.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.4
      - pytest==8.3.3
      - pytz==2024.2
      - pyvirtualdisplay==3.0
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - ray==2.7.1
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.9.4
      - rlds==0.1.8
      - rpds-py==0.20.1
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.0
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - simpleitk==2.4.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.14.0
      - termcolor==2.4.0
      - tfp-nightly==0.22.0.dev20231002
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.9.12
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.0.2
      - torch==2.1.1
      - torchio==0.20.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - transformers==4.36.0
      - transforms3d==0.4.1
      - triton==2.1.0
      - typer==0.13.1
      - typing-extensions==4.5.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.16.1
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - werkzeug==3.0.6
      - wrapt==1.16.0
      - zarr==2.16.1
